### ISSUE TITLE
configurable sliding window

### ISSUE THREAD

**Issue by thraxil** [rubyist/circuitbreaker#25]
The size/granularity of the sliding window for a breaker is hard-coded (https://github.com/rubyist/circuitbreaker/blob/master/circuitbreaker.go#L135). It would be nice to be able to configure that when creating a new breaker.

If I submit a PR for that, are you interested? I think if fields are added to `Options`, it can be done in a backwards-compatible manner.

**Comment by rubyist** [comment]
Sure that sounds cool.
