### ISSUE TITLE
HTTPClient Do Problem

### ISSUE THREAD

**Issue by ryanmurf** [rubyist/circuitbreaker#29]
I am using circuit.NewHTTPClient and was wondering what you think about this.

```
client = circuit.NewHTTPClient(time.Second*5, 10, nil)
response, err := client.Do(request)
if err != nil {
	return
}
defer response.Body.Close()
```
I get this error message on the defer
2015/09/02 01:39:50 http: panic serving 10.0.8.48:36515: runtime error: invalid memory address or nil pointer dereference

I haven't tested this but I think that the call is timing out. This means that a nil response body and nil error is returned. I think that the error is not being returned properly.

```
func (c *HTTPClient) Do(req *http.Request) (*http.Response, error) {
	var resp *http.Response
	var err error
	breaker := c.breakerLookup(req.URL.String())
	breaker.Call(func() error {
		resp, err = c.Client.Do(req)
		return err
	}, c.timeout)
	return resp, err
}
```

should look like this

```
func (c *HTTPClient) Do(req *http.Request) (*http.Response, error) {
	var resp *http.Response
	var err error
	breaker := c.breakerLookup(req.URL.String())
	err = breaker.Call(func() error {
		resp, err = c.Client.Do(req)
		return err
	}, c.timeout)
	return resp, err
}
```

**Comment by paddie** [comment]
That makes a lot of sense. I'm running into the same issue right now.. You might as well make that into a pull-request.

**Comment by rubyist** [comment]
Sorry, I overlooked this. You're right, it wasn't properly returning the error. I've fixed this in master, thanks for the report!

**Comment by paddie** [comment]
<3
