### ISSUE TITLE
No lock protection for breaker in multiaccess environment

### ISSUE THREAD

**Issue by ciscoalfli** [rubyist/circuitbreaker#34]
Looking at the code, there is no protection against using a circuit in a multithreaded environment.
There are locks in panel for Add()/Get() but not for circuits themselves. To avoid Data Race, a mutex
lock was placed around the (*Breaker).Call(). Is there a better way to do it?

Got the following in our test:
WARNING: DATA RACE
Write by goroutine 60:
  github.com/rubyist/circuitbreaker.(*Breaker).Success()
      /home/vagrant/rio-workspace/src/github.com/rubyist/circuitbreaker/circuitbreaker.go:266 +0xb1
  github.com/rubyist/circuitbreaker.(*Breaker).Call()
      /home/vagrant/rio-workspace/src/github.com/rubyist/circuitbreaker/circuitbreaker.go:326 +0x124

Previous write by goroutine 57:
  github.com/rubyist/circuitbreaker.(*Breaker).Success()
      /home/vagrant/rio-workspace/src/github.com/rubyist/circuitbreaker/circuitbreaker.go:266 +0xb1
  github.com/rubyist/circuitbreaker.(*Breaker).Call()
      /home/vagrant/rio-workspace/src/github.com/rubyist/circuitbreaker/circuitbreaker.go:326 +0x124
  github.comcast.com/viper-cog/rio-a8-updater/breaker.CallCircuitBreaker()

**Comment by rubyist** [comment]
Ah, I think the problem is around setting the next backoff in the `Success` and `Fail` functions. `Call` wouldn't be the right place to lock because the race will still happen when doing the more manual style. I've got some time this evening I can put together a fix, nice catch!
